### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by sanaz1376**
d0k3:master

### CODE REVIEW

**Comment by sanaz1376** [comment]
https://github.com/d0k3/OpenFirmInstaller/pull/6#issue-1499509046

**Comment by sanaz1376** [comment]
sanaz1376/OpenFirmInstaller

**Comment by sanaz1376** [comment]
https://github.com/d0k3/OpenFirmInstaller/pull/6#issue-1499509046

**Comment by sanaz1376** [comment]
https://github.com/d0k3/OpenFirmInstaller/pull/6#issue-1499509046

**Comment by sanaz1376** [comment]
#3

**Comment by sanaz1376** [comment]
sanaz1376:patch-1

**Comment by sanaz1376** [comment]
sanaz1376:patch-1

**Comment by sanaz1376** [comment]
sanaz1376:patch-1

**Comment by sanaz1376** [comment]
https://github.com/d0k3/OpenFirmInstaller/pull/6#issue-1499509046

**Comment by sanaz1376** [comment]
https://github.com/d0k3/OpenFirmInstaller/pull/6#issue-1499509046

**Comment by d0k3** [comment]
I wonder what happened here...

**Pull request closed without merging**
